CREATE DATABASE kitchen;

CREATE TABLE tableware (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    qty INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE office (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    starting_year INT NOT NULL,
    PRIMARY KEY(id)
);

-- En saanut tätä toimimaan, mutta tajusin jälkeenpäin, että idea oli varmaan tehdä database suoraan sql lauseella ja sen jälkeen lisätä taulu tämän tyyppisellä komennolla:
CREATE TABLE [kitchen.][public.]office (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    starting_year INT NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE tableware
ADD office_id INT;

ALTER TABLE tableware ADD FOREIGN KEY (office_id) REFERENCES office(id)

UPDATE tableware
SET office_id = 1
WHERE id<8;